# Custom Language File for Launcher Customizer

[ejs.app]
title = "뉴플레이 런처"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalzi/HeliosLauncher"
supportLink = "https://github.com/morebetter-dev/NewPlay-launcher/issues"

[ejs.welcome]
welcomeHeader = "뉴플레이에 오신 것을 환영합니다"
welcomeDescription = "Minecraft 1.21.4와 필수 모드를 자동으로 준비합니다."
welcomeDescCTA = "Microsoft 계정으로 로그인하면 바로 시작할 수 있습니다."
